// Code generated from vercel-labs/just-bash command help definitions; DO NOT EDIT.
// Upstream commit: 2b316eb26b3f3e832e2cf3994d4fef160d5eb8e4.
package commandhelp

var catalog = map[string]Info{
	"awk": {
		Name:    "awk",
		Summary: "pattern scanning and text processing language",
		Usage:   "awk [OPTION]... 'program' [FILE]...",
		Description: []string{
			"Runs an in-process AWK interpreter over stdin or virtual filesystem files. Supports BEGIN/END, pattern-action rules, fields, variables, associative arrays, user functions, print/printf, getline-style record reads, next/nextfile, and common string/math built-ins.",
		},
		Options: []string{
			"-F SEP       use SEP as the input field separator",
			"-v VAR=VAL   assign VAR before program execution",
			"-f FILE      read the AWK program from FILE in the virtual filesystem",
			"    --help   display this help and exit",
		},
		Notes: []string{
			"Advanced awk features such as pipes/co-processes, system(), close(), fflush(), extension loading, locale-specific formatting, and full replacement back-reference semantics are intentionally deferred to keep execution inside gash capabilities.",
		},
	},
	"base64": {
		Name:    "base64",
		Summary: "base64 encode/decode data and print to standard output",
		Usage:   "base64 [OPTION]... [FILE]",
		Options: []string{
			"-d, --decode    decode data",
			"-w, --wrap=COLS wrap encoded lines after COLS character (default 76, 0 to disable)",
			"    --help      display this help and exit",
		},
	},
	"basename": {
		Name:    "basename",
		Summary: "strip directory and suffix from filenames",
		Usage:   "basename NAME [SUFFIX]\\nbasename OPTION... NAME...",
		Options: []string{
			"-a, --multiple   support multiple arguments",
			"-s, --suffix=SUFFIX  remove a trailing SUFFIX",
			"    --help       display this help and exit",
		},
	},
	"cat": {
		Name:    "cat",
		Summary: "concatenate files and print on the standard output",
		Usage:   "cat [OPTION]... [FILE]...",
		Options: []string{
			"-A, --show-all         equivalent to -vET",
			"-b, --number-nonblank  number nonempty output lines, overrides -n",
			"-e                     equivalent to -vE",
			"-E, --show-ends        display $ at end of each line",
			"-n, --number           number all output lines",
			"-s, --squeeze-blank    suppress repeated empty output lines",
			"-t                     equivalent to -vT",
			"-T, --show-tabs        display TAB characters as ^I",
			"-u                     (ignored)",
			"-v, --show-nonprinting use ^ and M- notation, except for LFD and TAB",
			"    --help             display this help and exit",
		},
	},
	"chmod": {
		Name:    "chmod",
		Summary: "change file mode bits",
		Usage:   "chmod [OPTIONS] MODE FILE...",
		Options: []string{
			"-R      change files recursively",
			"-v      output a diagnostic for every file processed",
			"    --help display this help and exit",
		},
	},
	"cmp": {
		Name:    "cmp",
		Summary: "compare two files byte by byte",
		Usage:   "cmp [OPTION]... FILE1 [FILE2 [SKIP1 [SKIP2]]]",
		Options: []string{
			"-s, --silent, --quiet       suppress all normal output",
			"-l, --verbose               output byte numbers and differing byte values",
			"-n, --bytes=LIMIT           compare at most LIMIT bytes",
			"-i, --ignore-initial=SKIP   skip initial bytes; use SKIP1:SKIP2 for separate values",
			"    --help                  display this help and exit",
		},
	},
	"cksum": {
		Name:    "cksum",
		Summary: "print POSIX CRC checksums and byte counts",
		Usage:   "cksum [--] [FILE]...",
		Description: []string{
			"Reads stdin when no FILE is given. A FILE of - also reads stdin at that operand position.",
		},
		Options: []string{
			"--             end option parsing",
			"    --help     display this help and exit",
		},
		Notes: []string{
			"Uses the POSIX cksum CRC algorithm, including the input length in the checksum.",
		},
	},
	"clear": {
		Name:    "clear",
		Summary: "clear the terminal screen",
		Usage:   "clear [OPTIONS]",
		Options: []string{
			"    --help display this help and exit",
		},
	},
	"column": {
		Name:    "column",
		Summary: "columnate lists",
		Usage:   "column [OPTION]... [FILE]...",
		Options: []string{
			"-t           Create a table (determine columns from input)",
			"-s SEP       Input field delimiter (default: whitespace)",
			"-o SEP       Output field delimiter (default: two spaces)",
			"-c WIDTH     Output width for fill mode (default: 80)",
			"-n           Don't merge multiple adjacent delimiters",
		},
	},
	"comm": {
		Name:    "comm",
		Summary: "compare two sorted files line by line",
		Usage:   "comm [OPTION]... FILE1 FILE2",
		Options: []string{
			"-1             suppress column 1 (lines unique to FILE1)",
			"-2             suppress column 2 (lines unique to FILE2)",
			"-3             suppress column 3 (lines that appear in both files)",
			"    --help     display this help and exit",
		},
	},
	"cp": {
		Name:    "cp",
		Summary: "copy files and directories",
		Usage:   "cp [OPTION]... SOURCE... DEST",
		Options: []string{
			"-r, -R, --recursive  copy directories recursively",
			"-n, --no-clobber     do not overwrite an existing file",
			"-p, --preserve       preserve file attributes",
			"-v, --verbose        explain what is being done",
			"    --help           display this help and exit",
		},
	},
	"cut": {
		Name:    "cut",
		Summary: "remove sections from each line of files",
		Usage:   "cut [OPTION]... [FILE]...",
		Options: []string{
			"-c LIST              select only these characters",
			"-d DELIM             use DELIM instead of TAB for field delimiter",
			"-f LIST              select only these fields",
			"-s, --only-delimited  do not print lines without delimiters",
			"    --help           display this help and exit",
		},
	},
	"dirname": {
		Name:    "dirname",
		Summary: "strip last component from file name",
		Usage:   "dirname [OPTION] NAME...",
		Options: []string{
			"    --help       display this help and exit",
		},
	},
	"date": {
		Name:    "date",
		Summary: "print or set the system date and time",
		Usage:   "date [OPTION]... [+FORMAT]",
		Options: []string{
			"-u, --utc        print or parse dates in UTC",
			"-d, --date=TEXT  display time described by TEXT instead of now",
		},
		Notes: []string{
			"Gash supports common GNU-style strftime directives and deterministic clock hooks; setting the system clock is intentionally unsupported.",
		},
	},
	"diff": {
		Name:    "diff",
		Summary: "compare files line by line",
		Usage:   "diff [OPTION]... FILE1 FILE2",
		Options: []string{
			"-u, --unified     output unified diff format (default)",
			"-q, --brief       report only whether files differ",
			"-s, --report-identical-files  report when files are the same",
			"-i, --ignore-case  ignore case differences",
			"    --help        display this help and exit",
		},
		Notes: []string{
			"Uses gash's Go unified-diff formatter; large-file hunk grouping may differ from upstream jsdiff output.",
		},
	},
	"du": {
		Name:    "du",
		Summary: "estimate file space usage",
		Usage:   "du [OPTION]... [FILE]...",
		Options: []string{
			"-a          write counts for all files, not just directories",
			"-h          print sizes in human readable format",
			"-s          display only a total for each argument",
			"-c          produce a grand total",
			"--max-depth=N  print total for directory only if N or fewer levels deep",
			"    --help  display this help and exit",
		},
	},
	"env": {
		Name:    "env",
		Summary: "run a program in a modified environment",
		Usage:   "env [OPTION]... [NAME=VALUE]... [COMMAND [ARG]...]",
		Options: []string{
			"-i, --ignore-environment  start with an empty environment",
			"-u NAME, --unset=NAME     remove NAME from the environment",
			"    --help                display this help and exit",
		},
	},
	"expr": {
		Name:    "expr",
		Summary: "evaluate expressions",
		Usage:   "expr EXPRESSION",
		Description: []string{
			"Supports just-bash-compatible arithmetic, comparison, boolean, string, and regular expression operators.",
		},
		Options: []string{
			"    --help       display this help and exit",
		},
		Notes: []string{
			"Regular expressions use Go's linear-time regexp engine, so syntax and unsupported constructs may differ from upstream RE2JS diagnostics.",
		},
	},
	"expand": {
		Name:    "expand",
		Summary: "convert tabs to spaces",
		Usage:   "expand [OPTION]... [FILE]...",
		Options: []string{
			"-t N        Use N spaces per tab (default: 8)",
			"-t LIST     Use comma-separated list of tab stops",
			"-i          Only convert leading tabs on each line",
		},
	},
	"file": {
		Name:    "file",
		Summary: "determine file type",
		Usage:   "file [OPTION]... FILE...",
		Options: []string{
			"-b, --brief          do not prepend filenames to output",
			"-i, --mime           output MIME type strings",
			"-L, --dereference    follow symlinks",
			"    --help           display this help and exit",
		},
	},
	"find": {
		Name:    "find",
		Summary: "search for files in a directory hierarchy",
		Usage:   "find [PATH...] [EXPRESSION]",
		Options: []string{
			"-name PATTERN    match file basename using a glob",
			"-iname PATTERN   like -name, but case-insensitive",
			"-path PATTERN    match the whole found path using a glob",
			"-ipath PATTERN   like -path, but case-insensitive",
			"-regex PATTERN   match the whole found path using a regular expression",
			"-type [f|d]      match regular files or directories",
			"-empty           match empty files or directories",
			"-mtime N         match modification age in days (+N, -N supported)",
			"-newer FILE      match files newer than FILE",
			"-size N[c|k|M|G] match by size (default unit is 512-byte blocks)",
			"-perm MODE       match permission bits (MODE, -MODE, /MODE)",
			"-maxdepth N      descend at most N levels below each start point",
			"-mindepth N      do not apply tests/actions above depth N",
			"-depth           process directory contents before directory itself",
			"-prune           do not descend into this directory",
			"-not, !          negate the following expression",
			"-a, -and         logical AND (default)",
			"-o, -or          logical OR",
			"-print           print the full file name (default action)",
			"-print0          print the full file name followed by a null character",
			"-printf FORMAT   print FORMAT directives: %f %h %p %P %s %d %m %M %t %T",
			"-delete          delete found files/directories (implies -depth)",
			"-exec CMD {} ;   unsupported in gash find; host PATH execution is disabled",
			"    --help       display this help and exit",
		},
	},
	"factor": {
		Name:    "factor",
		Summary: "factor non-negative decimal integers",
		Usage:   "factor [NUMBER]...",
		Description: []string{
			"Prints each NUMBER followed by its prime factors. With no arguments, reads whitespace-separated numbers from standard input.",
		},
		Options: []string{
			"    --help   display this help and exit",
		},
		Notes: []string{
			"Inputs are limited to 1000000000000 to bound trial-division work.",
			"Zero and one have no prime factors and are printed as '0:' and '1:'.",
		},
	},
	"fgrep": {
		Name:    "fgrep",
		Summary: "print lines that match fixed strings",
		Usage:   "fgrep [OPTION]... PATTERN [FILE]...",
		Description: []string{
			"Equivalent to grep -F: PATTERN is matched as literal text, not as a regular expression.",
		},
		Options: []string{
			"-i, --ignore-case        ignore case distinctions",
			"-v, --invert-match       select non-matching lines",
			"-w, --word-regexp        match only whole words",
			"-x, --line-regexp        match only whole lines",
			"-c, --count              print only a count of matching lines",
			"-l, --files-with-matches print only names of files with matches",
			"-L, --files-without-match print names of files with no matches",
			"-m NUM, --max-count=NUM  stop after NUM matches",
			"-n, --line-number        print line number with output lines",
			"-h, --no-filename        suppress the file name prefix on output",
			"-o, --only-matching      show only nonempty parts of lines that match",
			"-q, --quiet, --silent    suppress all normal output",
			"-r, -R, --recursive      search directories recursively",
			"-A NUM                   print NUM lines of trailing context",
			"-B NUM                   print NUM lines of leading context",
			"-C NUM                   print NUM lines of context",
			"-e PATTERN               use PATTERN for matching",
			"    --include=GLOB       search only files matching GLOB",
			"    --exclude=GLOB       skip files matching GLOB",
			"    --exclude-dir=DIR    skip directories matching DIR",
			"    --help               display this help and exit",
		},
	},
	"fold": {
		Name:    "fold",
		Summary: "wrap each input line to fit in specified width",
		Usage:   "fold [OPTION]... [FILE]...",
		Options: []string{
			"-w WIDTH    Use WIDTH columns instead of 80",
			"-s          Break at spaces",
			"-b          Count bytes rather than columns",
		},
	},
	"grep": {
		Name:    "grep",
		Summary: "print lines that match patterns",
		Usage:   "grep [OPTION]... PATTERN [FILE]...",
		Options: []string{
			"-E, --extended-regexp    PATTERN is an extended regular expression",
			"-P, --perl-regexp        PATTERN is a Perl regular expression",
			"-F, --fixed-strings      PATTERN is a set of newline-separated strings",
			"-i, --ignore-case        ignore case distinctions",
			"-v, --invert-match       select non-matching lines",
			"-w, --word-regexp        match only whole words",
			"-x, --line-regexp        match only whole lines",
			"-c, --count              print only a count of matching lines",
			"-l, --files-with-matches print only names of files with matches",
			"-L, --files-without-match print names of files with no matches",
			"-m NUM, --max-count=NUM  stop after NUM matches",
			"-n, --line-number        print line number with output lines",
			"-h, --no-filename        suppress the file name prefix on output",
			"-o, --only-matching      show only nonempty parts of lines that match",
			"-q, --quiet, --silent    suppress all normal output",
			"-r, -R, --recursive      search directories recursively",
			"-A NUM                   print NUM lines of trailing context",
			"-B NUM                   print NUM lines of leading context",
			"-C NUM                   print NUM lines of context",
			"-e PATTERN               use PATTERN for matching",
			"    --include=GLOB       search only files matching GLOB",
			"    --exclude=GLOB       skip files matching GLOB",
			"    --exclude-dir=DIR    skip directories matching DIR",
			"    --help               display this help and exit",
		},
	},
	"gunzip": {
		Name:    "gunzip",
		Summary: "expand gzip-compressed files",
		Usage:   "gunzip [OPTION]... [FILE]...",
		Options: []string{
			"-c, --stdout      write on standard output",
			"-t, --test        test compressed file integrity",
			"    --help        display this help and exit",
		},
		Notes: []string{
			"Alias-style gzip decompression implemented in-process; advanced gzip flags and source removal semantics are intentionally deferred.",
		},
	},
	"gzip": {
		Name:    "gzip",
		Summary: "compress or expand files",
		Usage:   "gzip [OPTION]... [FILE]...",
		Options: []string{
			"-c, --stdout      write on standard output, keep input files",
			"-d, --decompress  decompress",
			"-t, --test        test compressed file integrity",
			"-1..-9            compression level",
			"    --help        display this help and exit",
		},
		Notes: []string{
			"Input and output stay inside gash streams and virtual files. Header-name preservation, input-file removal, and uncommon gzip flags are intentionally deferred.",
		},
	},
	"history": {
		Name:    "history",
		Summary: "display the command history list",
		Usage:   "history",
		Notes: []string{
			"Interactive history storage is intentionally deferred; non-interactive gash executions report an empty history.",
		},
	},
	"head": {
		Name:    "head",
		Summary: "output the first part of files",
		Usage:   "head [OPTION]... [FILE]...",
		Options: []string{
			"-c, --bytes=NUM    print the first NUM bytes",
			"-n, --lines=NUM    print the first NUM lines (default 10)",
			"-q, --quiet        never print headers giving file names",
			"-v, --verbose      always print headers giving file names",
			"    --help         display this help and exit",
		},
	},
	"help": {
		Name:    "help",
		Summary: "display information about gash built-in commands",
		Usage:   "help [COMMAND...]",
		Notes: []string{
			"Standalone help is provided without inventing global --help semantics for commands that do not have registered help text.",
		},
	},

	"html-to-markdown": {
		Name:    "html-to-markdown",
		Summary: "convert HTML documents to Markdown",
		Usage:   "html-to-markdown [FILE]...",
		Description: []string{
			"Converts HTML from stdin or virtual filesystem files to Markdown using an in-process parser. Supports headings, paragraphs, emphasis, links, images, lists, blockquotes, and code blocks.",
		},
		Options: []string{
			"    --help       display this help and exit",
		},
		Notes: []string{
			"Script/style content is ignored and javascript:/data: links are not emitted. Advanced upstream conversion plugins and exact whitespace formatting are intentionally deferred.",
		},
	},
	"id": {
		Name:    "id",
		Summary: "print the fixed gash virtual user and group identity",
		Usage:   "id [OPTION]...",
		Description: []string{
			"Prints gash's deterministic virtual identity: user and primary group user, with uid and gid 1000. User operands are not supported.",
		},
		Options: []string{
			"-u, --user     print only the effective user ID",
			"-g, --group    print only the effective group ID",
			"-G, --groups   print all group IDs",
			"-n, --name     print names instead of numbers; requires exactly one selector",
			"    --help     display this help and exit",
		},
		Notes: []string{
			"Identity is fixed and does not use host credentials, the host user database, or environment variables.",
			"Exactly one of --user, --group, or --groups may be selected. Operands and other options are rejected.",
		},
	},
	"install": {
		Name:    "install",
		Summary: "copy files and set attributes",
		Usage:   "install [OPTION]... SOURCE... DEST\ninstall -d [OPTION]... DIRECTORY...",
		Description: []string{
			"Copies regular files inside the virtual filesystem using mode 0755 by default.",
		},
		Options: []string{
			"-D                 create missing destination parent directories",
			"-d, --directory    create directories and parents instead of copying",
			"-m, --mode=MODE    set octal or supported symbolic permission mode",
			"    --              end option parsing",
			"    --help          display this help and exit",
		},
		Notes: []string{
			"Ownership/group, stripping, SELinux contexts, and timestamp preservation are explicitly unsupported.",
		},
	},
	"join": {
		Name:    "join",
		Summary: "join lines of two files on a common field",
		Usage:   "join [OPTION]... FILE1 FILE2",
		Options: []string{
			"-1 FIELD     Join on this FIELD of file 1 (default: 1)",
			"-2 FIELD     Join on this FIELD of file 2 (default: 1)",
			"-t CHAR      Use CHAR as input and output field separator",
			"-a FILENUM   Also print unpairable lines from file FILENUM (1 or 2)",
			"-v FILENUM   Like -a but only output unpairable lines",
			"-e STRING    Replace missing fields with STRING",
			"-o FORMAT    Output format (comma-separated list of FILENUM.FIELD)",
			"-i           Ignore case when comparing fields",
		},
	},
	"ln": {
		Name:    "ln",
		Summary: "make links between files",
		Usage:   "ln [OPTIONS] TARGET LINK_NAME",
		Options: []string{
			"-s      create a symbolic link instead of a hard link",
			"-f      remove existing destination files",
			"-n      treat LINK_NAME as a normal file if it is a symbolic link to a directory",
			"-v      print name of each linked file",
			"    --help display this help and exit",
		},
	},
	"ls": {
		Name:    "ls",
		Summary: "list directory contents",
		Usage:   "ls [OPTION]... [FILE]...",
		Options: []string{
			"-a, --all            do not ignore entries starting with .",
			"-A, --almost-all     do not list . and ..",
			"-d, --directory      list directories themselves, not their contents",
			"-F, --classify       append indicator (one of */=>@) to entries",
			"-h, --human-readable with -l, print sizes like 1K 234M 2G etc.",
			"-l                   use a long listing format",
			"-r, --reverse        reverse order while sorting",
			"-R, --recursive      list subdirectories recursively",
			"-S                   sort by file size, largest first",
			"-t                   sort by time, newest first",
			"-1                   list one file per line",
			"    --help           display this help and exit",
		},
	},
	"mktemp": {
		Name:    "mktemp",
		Summary: "create a temporary file or directory",
		Usage:   "mktemp [OPTION]... [TEMPLATE]",
		Description: []string{
			"Create inside the configured virtual filesystem. TEMPLATE must end with at least three X characters in its final component.",
		},
		Options: []string{
			"-d                 create a directory instead of a file",
			"-p DIR             create in DIR using a basename template",
			"    --tmpdir=DIR    create in DIR using a basename template",
			"    --help          display this help and exit",
		},
		Notes: []string{
			"Flags such as -u, -q, ownership, and suffix options are intentionally unsupported.",
		},
	},
	"mv": {
		Name:    "mv",
		Summary: "move (rename) files",
		Usage:   "mv [OPTION]... SOURCE... DEST",
		Options: []string{
			"-f, --force       do not prompt before overwriting",
			"-n, --no-clobber  do not overwrite an existing file",
			"-v, --verbose     explain what is being done",
			"    --help        display this help and exit",
		},
	},
	"nl": {
		Name:    "nl",
		Summary: "number lines of files",
		Usage:   "nl [OPTION]... [FILE]...",
		Options: []string{
			"-b STYLE     Body numbering style: a (all), t (non-empty), n (none)",
			"-n FORMAT    Number format: ln (left), rn (right), rz (right zeros)",
			"-w WIDTH     Number width (default: 6)",
			"-s SEP       Separator after number (default: TAB)",
			"-v START     Starting line number (default: 1)",
			"-i INCR      Line number increment (default: 1)",
		},
	},
	"paste": {
		Name:    "paste",
		Summary: "merge lines of files",
		Usage:   "paste [OPTION]... [FILE]...",
		Options: []string{
			"-d, --delimiters=LIST   reuse characters from LIST instead of TABs",
			"-s, --serial            paste one file at a time instead of in parallel",
			"    --help              display this help and exit",
		},
	},
	"printenv": {
		Name:    "printenv",
		Summary: "print all or part of environment",
		Usage:   "printenv [OPTION]... [VARIABLE]...",
		Options: []string{
			"    --help       display this help and exit",
		},
	},
	"printf": {
		Name:    "printf",
		Summary: "format and print data",
		Usage:   "printf [-v var] FORMAT [ARGUMENT...]",
		Options: []string{
			"    -v var     assign the output to shell variable VAR rather than display it",
			"    --help     display this help and exit",
		},
	},
	"readlink": {
		Name:    "readlink",
		Summary: "print resolved symbolic links or canonical file names",
		Usage:   "readlink [OPTIONS] FILE...",
		Options: []string{
			"-f      canonicalize by following every symlink in every component of the given name recursively",
			"    --help display this help and exit",
		},
	},
	"realpath": {
		Name:    "realpath",
		Summary: "print canonical absolute virtual paths",
		Usage:   "realpath [OPTION]... FILE...",
		Options: []string{
			"-e, --canonicalize-existing  all path components must exist (default)",
			"-m, --canonicalize-missing   allow missing trailing path components",
			"    --help                   display this help and exit",
		},
		Notes: []string{
			"Paths and symbolic links are resolved only within gash's virtual filesystem.",
		},
	},
	"rev": {
		Name:    "rev",
		Summary: "reverse lines characterwise",
		Usage:   "rev [file ...]",
	},
	"rg": {
		Name:    "rg",
		Summary: "recursively search for a pattern",
		Usage:   "rg [OPTIONS] PATTERN [PATH ...]",
		Description: []string{
			"rg recursively searches directories for a regex pattern. Unlike grep, rg is recursive by default, skips hidden/binary files by default, and respects .gitignore-style filters.",
		},
		Options: []string{
			"-e, --regexp PATTERN     search for PATTERN (can be used multiple times)",
			"-f, --file FILE          read patterns from FILE, one per line",
			"-i, --ignore-case        case-insensitive search",
			"-s, --case-sensitive     case-sensitive search",
			"-S, --smart-case         smart case (default)",
			"-F, --fixed-strings      treat pattern as literal string",
			"-w, --word-regexp        match whole words only",
			"-x, --line-regexp        match whole lines only",
			"-v, --invert-match       select non-matching lines",
			"-c, --count              print count of matching lines per file",
			"    --count-matches      print count of individual matches per file",
			"-l, --files-with-matches print only file names with matches",
			"    --files-without-match print file names without matches",
			"    --files              list files that would be searched",
			"-o, --only-matching      print only matching parts",
			"-m, --max-count NUM      stop after NUM matches per file",
			"-q, --quiet              suppress output, exit 0 on match",
			"-n, --line-number        print line numbers",
			"-N, --no-line-number     do not print line numbers",
			"-I, --no-filename        suppress file name prefixes",
			"-H, --with-filename      always print file name prefixes",
			"-0, --null               use NUL as filename separator",
			"-b, --byte-offset        show byte offset of each match",
			"    --column             show column number of first match",
			"    --vimgrep            show vimgrep-style line/column output",
			"    --json               show JSON Lines output",
			"-A NUM, -B NUM, -C NUM   print context around matches",
			"-g, --glob GLOB          include/exclude files matching GLOB (!GLOB excludes)",
			"    --iglob GLOB         case-insensitive glob",
			"-t, --type TYPE          only search files of TYPE",
			"-T, --type-not TYPE      exclude files of TYPE",
			"    --type-add SPEC      add a type definition",
			"    --type-clear TYPE    clear a type definition",
			"-L, --follow             follow symbolic links",
			"-u, --unrestricted       reduce filtering (-u ignore, -uu hidden, -uuu binary)",
			"-a, --text               search binary files as text",
			"    --hidden             search hidden files and directories",
			"    --no-ignore          don't respect ignore files",
			"    --ignore-file FILE   add a custom ignore file",
			"-d, --max-depth NUM      descend at most NUM directories",
			"    --max-filesize SIZE  skip files larger than SIZE (K/M/G supported)",
			"    --stats              print basic search statistics",
			"    --help               display this help and exit",
		},
		Notes: []string{
			"Uses Go's regexp engine; PCRE2, gzip search, multiline matching, and external preprocessors are intentionally deferred.",
		},
	},
	"sed": {
		Name:    "sed",
		Summary: "stream editor for filtering and transforming text",
		Usage:   "sed [OPTION]... {script} [input-file]...",
		Options: []string{
			"-n, --quiet, --silent  suppress automatic printing of pattern space",
			"-e script              add the script to commands to be executed",
			"-f script-file         read script from file",
			"-i, --in-place         edit files in place",
			"-E, -r, --regexp-extended  use extended regular expressions",
			"    --help             display this help and exit",
		},
		Description: []string{
			"Commands: s/regexp/replacement/[flags], d, p, a\\ text, i\\ text, c\\ text, h, H, g, G, x, n, N, y/source/dest/, =, l, b, t, T, :label, q, Q.",
			"Addresses: N, $, /regexp/, N,M, first~step, and /regexp/,+N ranges.",
		},
	},
	"sha512sum": {
		Name:    "sha512sum",
		Summary: "compute and check SHA512 message digest",
		Usage:   "sha512sum [OPTION]... [FILE]...",
		Options: []string{
			"    --       end option parsing",
			"    --help   display this help and exit",
		},
		Notes: []string{
			"Reads from stdin when no FILE is given or when FILE is -. Digest verification options are not supported.",
		},
	},
	"sleep": {
		Name:    "sleep",
		Summary: "delay for a specified amount of time",
		Usage:   "sleep NUMBER[SUFFIX]",
		Options: []string{
			"    --help display this help and exit",
		},
	},
	"sort": {
		Name:    "sort",
		Summary: "sort lines of text files",
		Usage:   "sort [OPTION]... [FILE]...",
		Options: []string{
			"-f, --ignore-case    fold lower case to upper case characters",
			"-n, --numeric-sort   compare according to string numerical value",
			"-r, --reverse        reverse the result of comparisons",
			"-o, --output=FILE    write result to FILE instead of stdout",
			"-u, --unique         output only unique lines",
			"-k, --key=KEYDEF     sort via a key; KEYDEF gives location and type",
			"-t, --field-separator=SEP  use SEP as field separator",
			"    --help           display this help and exit",
		},
		Notes: []string{
			"Unsupported GNU sort options are omitted and rejected rather than silently ignored.",
		},
	},
	"split": {
		Name:    "split",
		Summary: "split a file into pieces",
		Usage:   "split [OPTION]... [FILE [PREFIX]]",
		Options: []string{
			"-l N         Put N lines per output file",
			"-b SIZE      Put SIZE bytes per output file (K, M, G suffixes)",
			"-n CHUNKS    Split into CHUNKS equal-sized files",
			"-d           Use numeric suffixes (00, 01, ...) instead of alphabetic",
			"-a LENGTH    Use suffixes of length LENGTH (default: 2)",
			"--additional-suffix=SUFFIX  Append SUFFIX to file names",
		},
	},
	"sqlite3": {
		Name:    "sqlite3",
		Summary: "SQLite database CLI",
		Usage:   "sqlite3 [OPTIONS] DATABASE [SQL]",
		Options: []string{
			"-list, -csv, -json, -line, -column, -table, -markdown, -tabs, -box, -quote, -html, -ascii",
			"-header, -noheader       show or hide column headers",
			"-separator SEP           field separator for list mode",
			"-newline SEP             row separator for list/tabs/quote modes",
			"-nullvalue TEXT          text for NULL values",
			"-readonly                execute without writing database changes back",
			"-bail                    stop on the first SQL error",
			"-echo                    print SQL before execution",
			"-cmd SQL                 run SQL before the main SQL/stdin script",
			"-version                 show SQLite version",
			"    --help, -help        display this help and exit",
		},
		Notes: []string{
			"Runs modernc.org/sqlite in-process without invoking host sqlite3. Database images are read from and written back to the gash virtual filesystem; extension loading, ATTACH, VACUUM INTO, and sqlite dot-commands are disabled. Gash uses Go context cancellation and SQLite limits instead of just-bash's sql.js worker protocol.",
		},
	},
	"stat": {
		Name:    "stat",
		Summary: "display file or file system status",
		Usage:   "stat [OPTION]... FILE...",
		Options: []string{
			"-c FORMAT   use the specified FORMAT instead of the default",
			"    --help  display this help and exit",
		},
	},
	"strings": {
		Name:    "strings",
		Summary: "print the sequences of printable characters in files",
		Usage:   "strings [OPTION]... [FILE]...",
		Options: []string{
			"-n MIN       Print sequences of at least MIN characters (default: 4)",
			"-t FORMAT    Print offset before each string (o=octal, x=hex, d=decimal)",
			"-a           Scan the entire file (default behavior)",
			"-e ENCODING  Select character encoding (s=7-bit, S=8-bit)",
		},
	},
	"tail": {
		Name:    "tail",
		Summary: "output the last part of files",
		Usage:   "tail [OPTION]... [FILE]...",
		Options: []string{
			"-c, --bytes=NUM    print the last NUM bytes",
			"-n, --lines=NUM    print the last NUM lines (default 10)",
			"-n +NUM            print starting from line NUM",
			"-q, --quiet        never print headers giving file names",
			"-v, --verbose      always print headers giving file names",
			"    --help         display this help and exit",
		},
	},
	"tar": {
		Name:    "tar",
		Summary: "create, list, and extract tar archives",
		Usage:   "tar -cf ARCHIVE FILE...\ntar -tf ARCHIVE\ntar -xf ARCHIVE",
		Options: []string{
			"-c, -t, -x       create, list, or extract an archive",
			"-f FILE          read/write archive FILE (- for stdin/stdout)",
			"-z               filter archive through gzip",
			"-C DIR           change virtual directory before operation",
			"-v               list processed files on stderr",
			"-O, --to-stdout  extract regular files to stdout",
			"--strip-components=N strip leading path components while extracting",
			"    --help       display this help and exit",
		},
		Notes: []string{
			"Runs entirely against gash's virtual filesystem. Extraction rejects absolute/traversal paths, unsafe symlink and hardlink escapes, unsupported entry types/codecs, and oversized archives. Advanced GNU tar flags and non-gzip codecs are intentionally deferred.",
		},
	},
	"tee": {
		Name:    "tee",
		Summary: "read from stdin and write to stdout and files",
		Usage:   "tee [OPTION]... [FILE]...",
		Options: []string{
			"-a, --append     append to the given FILEs, do not overwrite",
			"    --help       display this help and exit",
		},
	},
	"tr": {
		Name:    "tr",
		Summary: "translate or delete characters",
		Usage:   "tr [OPTION]... SET1 [SET2]",
		Options: []string{
			"-c, -C, --complement   use the complement of SET1",
			"-d, --delete           delete characters in SET1",
			"-s, --squeeze-repeats  squeeze repeated characters",
			"    --help             display this help and exit",
		},
	},
	"time": {
		Name:    "time",
		Summary: "run a command and report elapsed time",
		Usage:   "time COMMAND [ARG]...",
		Notes: []string{
			"Commands execute through the safe gash command path; CPU accounting is reported as zero rather than host process usage.",
		},
	},
	"timeout": {
		Name:    "timeout",
		Summary: "run a command with a time limit",
		Usage:   "timeout DURATION COMMAND [ARG]...",
		Options: []string{
			"DURATION accepts seconds by default, or s, m, h, d suffixes.",
		},
	},
	"tree": {
		Name:    "tree",
		Summary: "list contents of directories in a tree-like format",
		Usage:   "tree [OPTION]... [DIRECTORY]...",
		Options: []string{
			"-a          include hidden files",
			"-d          list directories only",
			"-L LEVEL    limit depth of directory tree",
			"-f          print full path prefix for each file",
			"    --help  display this help and exit",
		},
	},
	"umask": {
		Name:    "umask",
		Summary: "set or display the file creation mask",
		Usage:   "umask [-pS] [MODE]",
		Options: []string{
			"-p          display the mask as a reusable command",
			"-S          display the mask symbolically",
		},
		Notes: []string{
			"MODE may be an octal mask or a symbolic rwx permission mode.",
		},
	},
	"uname": {
		Name:    "uname",
		Summary: "print deterministic virtual system information",
		Usage:   "uname [OPTION]...",
		Description: []string{
			"Prints stable gash platform values without consulting the host operating system or architecture.",
		},
		Options: []string{
			"-a, --all             print all fields in GNU order",
			"-s, --kernel-name     print the kernel name (Gash)",
			"-n, --nodename        print the network node hostname (localhost)",
			"-r, --kernel-release  print the kernel release (1.0.0)",
			"-v, --kernel-version  print the kernel version (#1 gash)",
			"-m, --machine         print the machine hardware name (virtual)",
			"    --help            display this help and exit",
		},
		Notes: []string{
			"Combined short options are supported and fields are always emitted in s, n, r, v, m order.",
			"Processor, hardware-platform, and operating-system options are not supported.",
		},
	},
	"unexpand": {
		Name:    "unexpand",
		Summary: "convert spaces to tabs",
		Usage:   "unexpand [OPTION]... [FILE]...",
		Options: []string{
			"-t N        Use N spaces per tab (default: 8)",
			"-t LIST     Use comma-separated list of tab stops",
			"-a          Convert all sequences of blanks (not just leading)",
		},
	},
	"unlink": {
		Name:    "unlink",
		Summary: "remove one virtual filesystem file",
		Usage:   "unlink FILE",
		Description: []string{
			"Removes exactly one non-directory path through the configured virtual filesystem.",
		},
		Options: []string{
			"    --help   display this help and exit",
		},
		Notes: []string{
			"The filesystem must provide the remove capability; host filesystem paths are never used implicitly.",
		},
	},
	"uniq": {
		Name:    "uniq",
		Summary: "report or omit repeated lines",
		Usage:   "uniq [OPTION]... [INPUT [OUTPUT]]",
		Options: []string{
			"-c, --count        prefix lines by the number of occurrences",
			"-d, --repeated     only print duplicate lines",
			"-i, --ignore-case  ignore case when comparing",
			"-u, --unique       only print unique lines",
			"    --help         display this help and exit",
		},
	},
	"which": {
		Name:    "which",
		Summary: "locate a gash command",
		Usage:   "which COMMAND...",
		Notes: []string{
			"Only gash built-ins and shell entry points are reported; host PATH executables are never resolved.",
		},
	},
	"wc": {
		Name:    "wc",
		Summary: "print newline, word, and byte counts for each file",
		Usage:   "wc [OPTION]... [FILE]...",
		Options: []string{
			"-c, --bytes      print the byte counts",
			"-m, --chars      print the character counts",
			"-l, --lines      print the newline counts",
			"-w, --words      print the word counts",
			"    --help       display this help and exit",
		},
	},
	"xargs": {
		Name:    "xargs",
		Summary: "build and execute command lines from standard input",
		Usage:   "xargs [OPTION]... [COMMAND [INITIAL-ARGS]]",
		Options: []string{
			"-I REPLACE   replace occurrences of REPLACE with input",
			"-d DELIM     use DELIM as input delimiter (e.g., -d '\\n' for newline)",
			"-n NUM       use at most NUM arguments per command line",
			"-P NUM       run at most NUM processes at a time",
			"-0, --null   items are separated by null, not whitespace",
			"-t, --verbose  print commands before executing",
			"-r, --no-run-if-empty  do not run command if input is empty",
			"    --help   display this help and exit",
		},
	},
	"yq": {
		Name:    "yq",
		Summary: "process YAML with jq-style filters",
		Usage:   "yq [OPTIONS] [FILTER] [FILE]...",
		Description: []string{
			"Parses YAML documents in-process, normalizes them to JSON-like values, applies gojq filters, and writes YAML by default or JSON with -o=json.",
		},
		Options: []string{
			"-o=json, -j           output JSON instead of YAML",
			"-r, --raw-output      print string results without quoting",
			"-y, -P                output YAML (default)",
			"    --help            display this help and exit",
		},
		Notes: []string{
			"YAML anchors are resolved by gopkg.in/yaml.v3 without executing tags or constructing host objects. Round-trip comments/styles, update-in-place, XML/TOML formats, and full yq CLI parity are intentionally deferred.",
		},
	},
	"zcat": {
		Name:    "zcat",
		Summary: "decompress gzip files to standard output",
		Usage:   "zcat [FILE]...",
		Options: []string{
			"    --help        display this help and exit",
		},
		Notes: []string{
			"Equivalent to gunzip -c for gzip streams inside gash.",
		},
	},
}

func Lookup(name string) (Info, bool) {
	info, ok := catalog[name]
	return info, ok
}
